# Site settings
title: This Week I Learned
description: > # this means to ignore newlines until "baseurl:"
  Things we learned this week, mostly programming related.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://twilblog.github.io" # the base hostname & protocol for your site
twitter_username: twil_blog
github_username:  twilblog

# Build settings
markdown: kramdown
