# Site settings
title: This week I learned.
description: > # this means to ignore newlines until "baseurl:"
  Things we learned this week, mostly programming related.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://twilblog.github.io" # the base hostname & protocol for your site
twitter_username: twil_blog
github_username:  twilblog

# Build settings
markdown: kramdown

authors:
  sam:
    display_name: Sam Adams
    avatar: https://avatars1.githubusercontent.com/u/339671?s=200
    twitter: s_a_m_a_d_a_m_s
    github: sadams
  shaun:
    display_name: Shaun Donnelly
    avatar: https://pbs.twimg.com/profile_images/587287617928110081/gXMbalSp_200x200.jpg
    twitter: surfitscrollit
    github: shaundon
  scott:
    display_name: Scott Cunningham
    avatar: https://avatars0.githubusercontent.com/u/982046?v=3&s=200
  ben:
    display_name: Ben Doyle
    avatar: https://res-3.cloudinary.com/status-hero/image/upload/c_fill/v1437582322/ubqxl0tjuwryeunokzwp
    twitter: ben__doyle
    github: k3ypad
  andy:
    display_name: Andy Loucas
    avatar: https://avatars2.githubusercontent.com/u/3877562?v=3&s=200
